import { AppWrapper } from "@/components/context";
import "./globals.css";
import Head from "next/head";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* Language Detector API */}
        <meta
          httpEquiv="origin-trial"
          content="ApGOmyTbgqLf5IUITDWHfAV6gON9BSUL/QmlXmztCGiG84EfL5COmGBfha11XbUJahRDJNVabIZKnit2UBbhswMAAACDeyJvcmlnaW4iOiJodHRwczovL2FpLXRleHQtcHJvY2Vzc29yLW9tZWdhLnZlcmNlbC5hcHA6NDQzIiwiZmVhdHVyZSI6Ikxhbmd1YWdlRGV0ZWN0aW9uQVBJIiwiZXhwaXJ5IjoxNzQ5NTk5OTk5LCJpc1N1YmRvbWFpbiI6dHJ1ZX0="
        />
        {/* Tranlator API */}
        <meta
          httpEquiv="origin-trial"
          content="AlZJ9f8wkZLm1eXyKo8QdqHbGi6Zgse9iB1G/1P4o/GKTzFNsxf/VpucRtFYy47uTCdJ4q20hSbPflAE/JroOAwAAAB9eyJvcmlnaW4iOiJodHRwczovL2FpLXRleHQtcHJvY2Vzc29yLW9tZWdhLnZlcmNlbC5hcHA6NDQzIiwiZmVhdHVyZSI6IlRyYW5zbGF0aW9uQVBJIiwiZXhwaXJ5IjoxNzUzMTQyNDAwLCJpc1N1YmRvbWFpbiI6dHJ1ZX0="
        />
        {/* Summarization API */}
        <meta
          httpEquiv="origin-trial"
          content="ApywZEcawPu3bp6OLLTdoGZKtPjN5sKcNOYQ7FrAJbcOp/vfx7SNIZu8Zxj9gqcIPXzkGd5/KiS1HpvUvKee5gwAAABVeyJvcmlnaW4iOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJmZWF0dXJlIjoiQUlTdW1tYXJpemF0aW9uQVBJIiwiZXhwaXJ5IjoxNzUzMTQyNDAwfQ=="
        />
      </Head>
      <body suppressHydrationWarning>
        <AppWrapper>{children}</AppWrapper>
      </body>
    </html>
  );
}
